import numpy as np  
import pandas as pd 

import matplotlib as mpl
import matplotlib.pyplot as plt



df_can = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.csv')

print('Data read into a pandas dataframe!')

# df_can.head()
# print the dimensions of the dataframe
print(df_can.shape)
# set index to country to make it easier to identify and perform analysis
df_can.set_index('Country', inplace=True)
# we will create a years variable which contains a list of years that will help in plotting data

years=list(map(str,range(1980,2014)))

# we will group by continents and perform sum operation to find out the largest continent proportion of total number of immgrants to canda

df_continents = df_can.groupby('Continent', axis=0).sum()

#plotting a pie chart 

df_continents['Total'].plot(kind='pie',
                            figsize=(10, 7),
                            autopct='%1.1f%%', 
                            startangle=90,    
                            shadow=True,       
                            labels=None,         #  to turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
                            )

# scale the title up by 12% to match pctdistance
plt.title('Immigration to Canada by Continent [1980 - 2013]', y=1.12, fontsize = 15) 

plt.axis('equal') 

# add legend
plt.legend(labels=df_continents.index, loc='upper left', fontsize=7) 

plt.show()

# Create a box plot to visualize the distribution of the top 15 countries (based on total immigration) grouped by the decades 1980s, 1990s, and 2000s.

df_top15 = df_can.sort_values(['Total'], ascending=False, axis=0).head(15)

# intialize data variables for plotting 

# create a list of all years in decades 80's, 90's, and 00's
years_80s=list(map(str,range(1980,1990)))
years_90s=list(map(str,range(1990,2000)))
years_00s=list(map(str,range(2000,2010)))

# slice the original dataframe df_can to create a series for each decade
df_80s=df_top15.loc[:,years_80s].sum(axis=1)
df_90s=df_top15.loc[:,years_90s].sum(axis=1)
df_00s=df_top15.loc[:,years_00s].sum(axis=1)

# merge the three series into a new data frame
new_df=pd.DataFrame({'1980s': df_80s, '1990s': df_90s, '2000s':df_00s})

new_df.head()

# plotting the box plots
new_df.plot(kind='box',figsize=(10,7),color='red')
plt.title('Immigration from top 15 countries for decades 80s, 90s and 2000s')
plt.show()

# Create a scatter plot of the total immigration from Denmark, Norway, and Sweden to Canada from 1980 to 2013

# prepare data for plotting

df_countries=df_can.loc[['Denmark','Norway','Sweden'],years].transpose()
df_countries.head()

df_total=pd.DataFrame(df_countries.sum(axis=1))
df_total.head()

df_total.reset_index(inplace=True)
print(df_total.head())

    # rename columns
df_total.columns = ['year', 'total']

    # change column year from string to int to create scatter plot
df_total['year'] = df_total['year'].astype(int)

    # show resulting dataframe
df_total.head()

# plot the scatter plot 
df_total.plot(kind='scatter',x='year',y='total',figsize=(10,6),color='darkblue')

plt.title('Immigration from Denmark, Norway, and Sweden to Canada from 1980 - 2013')
plt.xlabel('Year')
plt.ylabel('Number of Immigrants')

plt.show()



